[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v
pythonpath = .

[pytest-asyncio]
mode = auto
asyncio_default_fixture_loop_scope = function