"""Type stubs for ghidra.app.decompiler module."""

from typing import Any

class DecompInterface:
    def __init__(self) -> None: ...
    def setOptions(self, options: Any) -> None: ...
    def toggleCCode(self, enabled: bool) -> None: ...
    def toggleSyntaxTree(self, enabled: bool) -> None: ...
    def setSimplificationStyle(self, style: str) -> None: ...
    def openProgram(self, program: Any) -> None: ...
    def decompileFunction(self, function: Any, timeout: int, monitor: Any) -> Any: ...
    def dispose(self) -> None: ...

class DecompileOptions:
    def __init__(self) -> None: ...
