"""Type stubs for java.util module (via JPype)."""

from typing import Any, TypeVar

T = TypeVar("T")

class ArrayList:
    def __init__(self) -> None: ...
    def add(self, item: Any) -> bool: ...
    def get(self, index: int) -> Any: ...
    def size(self) -> int: ...
    def __iter__(self) -> Any: ...
